Repository AIESEC-in-Japan/aiesecjp-web, pull requests merged in 2021-07, with the labels that each got.

#253 [TOP]TOPページの刷新と細かい修正一気にやります
  assets/images/ogx/planet-earth.svg
  assets/images/ogx/users.svg
  assets/images/ogx/zoom-in.svg
  assets/images/top/global-youth-dialogue.png
  assets/images/top/handshake.svg
  assets/images/top/map.svg
  assets/images/top/product-GT.png
  assets/images/top/product-GV.png
  assets/images/top/top-2.jpg
  assets/images/top/visa.svg
  components/Outgoing/Feature.vue
  components/base/IconInAssetsPath.vue
  components/top/AboutAiesec.vue
  components/top/MainView.vue
  components/top/OurPartners.vue
  components/top/OurPrograms.vue
  components/top/WhyWhat.vue
  components/top/carouselContent/1st.vue
  components/top/carouselContent/2nd.vue
  components/top/carouselContent/3rd.vue
  pages/index.vue
Labels: new feature, refactor

#255 [安全への取り組み]安全管理委員会の議事録を載せる
  assets/scss/_carousel.scss
  components/safety/Committee.vue
  components/top/WhyWhat.vue
  components/top/carouselContent/3rd.vue
  pages/safety/index.vue
Labels: new feature

#256 [Contact]問い合わせページの作成
  components/base/Footer.vue
  components/base/Header.vue
  components/contact-us/Form.vue
  components/global-youth-dialogue/Apply.vue
  pages/contact-us/index.vue
Labels: new feature

#257 [プレスルーム]仮で作成する。
  components/base/Footer.vue
  components/press/2021.vue
  pages/press/index.vue
Labels: new feature

#272 [BUG]Eventのデザインバグ とか諸々
  components/global-youth-dialogue/Apply.vue
  components/global-youth-dialogue/Detail.vue
  components/global-youth-dialogue/FixedFooter.vue
  components/global-youth-dialogue/Top.vue
Labels: bug

#271 ドロワーのアイコン表示を修正
  components/base/Header.vue
Labels: bug

#277 [refactor] process.browser の排除
  components/global-youth-dialogue/FixedFooter.vue
  plugins/windowSize.js
Labels: refactor

#278 [BUG]個人情報表示バグ #266
  components/privacy-policy/Descriptions.vue
Labels: refactor

#269 Create buildCheck.yml
  .github/workflows/buildCheck.yml
Labels: new feature
