Repository AIESEC-in-Japan/aiesecjp-web, pull requests merged in 2021-06, with the labels that each got.

#155 コーディングの心構えをdocsに書く。
  README.md
  docs/coding-rules.md
Labels: 開発基盤

#176 開発環境はこのプロジェクトについての説明を書きます
  README.md
Labels: 開発基盤

#178 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: 開発基盤

#164 lintを入れたい。
  .eslintrc.js
  components/about/AdvisorList.vue
  components/about/OfficerList.vue
  components/about/OrganizationInfo.vue
  components/base/Button.vue
  components/base/Footer.vue
  components/base/Header.vue
  components/incoming/AboutIcxIntern.vue
  components/incoming/CorporationInternship.vue
  components/incoming/IcxDetail.vue
  components/incoming/IcxTop.vue
  components/outgoing/OgxDetail.vue
  components/outgoing/OgxExperience.vue
  components/outgoing/OgxFeature.vue
  components/outgoing/OgxProgram.vue
  components/outgoing/OgxTop.vue
  components/privacy-policy/PrivacyPolicyDescriptions.vue
  components/privacy-policy/PrivacyPolicyTop.vue
  components/safety/SafetyDescriptions.vue
  components/safety/SafetyTop.vue
  components/top/AboutAiesec.vue
  components/top/MainView.vue
  components/top/OurPartners.vue
  components/top/OurPrograms.vue
  layouts/default.vue
  package.json
  pages/press/index.vue
  pages/privacy-policy/index.vue
  pages/safety/index.vue
  yarn.lock
Labels: 開発基盤

#165 CSS周りのコード規約を書きたい
  .stylelintrc
  assets/scss/_base.scss
  assets/scss/_mixin.scss
  assets/scss/_variable.scss
  assets/scss/main.scss
  components/about/AdvisorList.vue
  components/about/OfficerList.vue
  components/about/OrganizationInfo.vue
  components/base/Footer.vue
  components/base/Header.vue
  components/incoming/AboutIcxIntern.vue
  components/incoming/CorporationInternship.vue
  components/incoming/CorporationMerit.vue
  components/incoming/IcxDetail.vue
  components/incoming/IcxTop.vue
  components/outgoing/OgxDetail.vue
  components/outgoing/OgxExperience.vue
  components/outgoing/OgxFeature.vue
  components/outgoing/OgxProgram.vue
  components/outgoing/OgxTop.vue
  components/privacy-policy/PrivacyPolicyDescriptions.vue
  components/privacy-policy/PrivacyPolicyTop.vue
  components/safety/SafetyTop.vue
  components/top/AboutAiesec.vue
  components/top/OurPartners.vue
  layouts/default.vue
  package.json
  pages/press/index.vue
  yarn.lock
Labels: 開発基盤

#156 About usのページのリファクタリング
  assets/scss/_table.scss
  assets/scss/main.scss
  components/about/AdvisorList.vue
  components/about/OfficerList.vue
  components/about/OrganizationInfo.vue
Labels: good first issue

#182 企業ロゴの切り出し
  assets/2020corporation-logo/aus-be.png
  assets/2020corporation-logo/recruit-ms.jpg
  assets/README.md
  components/base/IconInAssetsPath.vue
  components/top/OurPartners.vue
Labels: good first issue

#185 unit-disallowed-list | Stylelint の導入
  .stylelintrc
  assets/scss/_base.scss
  components/base/Header.vue
  components/outgoing/OgxExperience.vue
  components/outgoing/OgxProgram.vue
  components/privacy-policy/PrivacyPolicyDescriptions.vue
  components/privacy-policy/PrivacyPolicyTop.vue
  components/safety/SafetyDescriptions.vue
  components/safety/SafetyTop.vue
  components/top/AboutAiesec.vue
  components/top/OurPrograms.vue
  layouts/default.vue
  package.json
  pages/press/_slug.vue
  pages/press/index.vue
Labels: 開発基盤

#207 vuetify js の導入
  README.md
  components/outgoing/OgxDetail.vue
  components/outgoing/OgxExperience.vue
  components/outgoing/OgxFeature.vue
  components/outgoing/OgxProgram.vue
  components/outgoing/OgxTop.vue
  nuxt.config.js
  package.json
  yarn.lock
Labels: new feature, 開発基盤

#206 yarn/gitについて追記
  README.md
Labels: documentation, ~30

#199 storyBookの導入
  .eslintignore
  .eslintrc.js
  .gitignore
  README.md
  components/Incoming/AboutIntern.vue
  components/Incoming/CorporationInternship.vue
  components/Incoming/CorporationMerit.vue
  components/Incoming/Detail.vue
  components/Incoming/Top.vue
  components/Outgoing/Detail.vue
  components/Outgoing/Experience.vue
  components/Outgoing/Feature.vue
  components/Outgoing/Program.vue
  components/Outgoing/Top.vue
  components/about/AdvisorList.vue
  components/about/OfficerList.vue
  components/about/OrganizationInfo.vue
  components/privacy-policy/Descriptions.vue
  components/privacy-policy/PolicyTop.vue
  components/safety/Descriptions.vue
  components/safety/Top.vue
  components/top/OurPartners.vue
  layouts/default.vue
  nuxt.config.js
  package.json
  pages/about/index.vue
  pages/incoming/index.vue
  pages/index.vue
  pages/outgoing/index.vue
  stories/SampleButton.stories.js
  stories/SampleButton.vue
  yarn.lock
Labels: 開発基盤

#226 [Global Youth Dialogue]Top
  assets/scss/_variable.scss
  components/base/Footer.vue
  components/base/Header.vue
  components/global-youth-dialogue/Top.vue
  pages/global-youth-dialogue/index.vue
  pages/incoming/index.vue
Labels: new feature

#227 [Global Youth Dialogue]detailの作成
  assets/images/global-youth-dialogue/GlobalYouthDialogueTop.jpg
  assets/images/global-youth-dialogue/global-youth-dialogue-logo-white.png
  assets/images/global-youth-dialogue/global.svg
  assets/images/global-youth-dialogue/message.svg
  assets/images/global-youth-dialogue/notification.svg
  assets/images/global-youth-dialogue/typing.svg
  assets/scss/_base.scss
  components/global-youth-dialogue/Detail.vue
  pages/global-youth-dialogue/index.vue
Labels: new feature

#228 [Global Youth Dialogue]案内
  components/base/CommonColor.js
  components/base/RoundButton.vue
  components/global-youth-dialogue/Detail.vue
  components/global-youth-dialogue/apply.vue
  pages/global-youth-dialogue/index.vue
Labels: new feature

#229 [Global Youth Dialogue] 参加者の声はこちら
  components/global-youth-dialogue/Voice.vue
  components/global-youth-dialogue/apply.vue
  pages/global-youth-dialogue/index.vue
Labels: new feature

#230 [Global Youth Dialogue]　公式LINEへのリンクの固定footer
  components/base/RoundButton.vue
  components/global-youth-dialogue/FixedFooter.vue
  components/global-youth-dialogue/Voice.vue
  components/global-youth-dialogue/apply.vue
  pages/global-youth-dialogue/index.vue
Labels: new feature

#241 [RWD対応] ICXの対応
  assets/scss/_variable.scss
  components/Incoming/AboutIntern.vue
  components/Incoming/CorporationInternship.vue
  components/Incoming/CorporationMerit.vue
  components/Incoming/Detail.vue
  components/Incoming/Top.vue
  components/top/MainView.vue
Labels: refactor

#240 [RWD対応] 個人情報
  components/privacy-policy/PolicyTop.vue
Labels: new feature, refactor

#239 [OGX]不要なリンク削除
  components/Outgoing/Program.vue
Labels: refactor

#243 [RWD対応] OGXの対応 とOGXまわり色々
  components/Outgoing/Detail.vue
  components/Outgoing/Experience.vue
  pages/outgoing/index.vue
Labels: refactor

#248 [RWD対応] 安全への取り組み
  components/Outgoing/Detail.vue
  components/safety/Descriptions.vue
  components/safety/Top.vue
Labels: refactor
